name       : prelink
version    : 20130503
release    : 1
source     :
    - http://people.redhat.com/jakub/prelink/prelink-20130503.tar.bz2 : 6339c7605e9b6f414d1be32530c9c8011f38820d36431c8a62e8674ca37140f0
license    : GPL-2.0
component  : kernel.image
summary    : ELF prelinking utility to speed up dynamic linking.
description: |
    ELF prelinking utility to speed up dynamic linking.
    This package is provided only for prelinking the Solus initramfs
builddeps  :
    - pkgconfig(libelf)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
